version: '3'
services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic
    container_name: borgmatic
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro            # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository      # backup target
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/  # borgmatic config file(s) + crontab.txt
      - ${VOLUME_BORGMATIC_STATE}:/root/.borgmatic # borgmatic state files
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg   # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh                   # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg     # checksums used for deduplication
    environment:
      - TZ=${TZ}
    secrets:
      - BORG_PASSPHRASE
      - BORGMATIC_REPO
      - BORGMATIC_SSH_KEY

# Secrets (https://docs.docker.com/compose/use-secrets/)
# Any secrets prefixed with BORG will be loaded into the environment when the borgmatic container runs.
# Generate docker secrets using: echo -n "secret" | docker secret create BORG_PASSPHRASE -

secrets:
  BORGMATIC_REPO:                                 # borg repository
    external: true
  BORG_PASSPHRASE:                                # passphrase for the borg repository
    external: true
  BORGMATIC_SSH_KEY:                              # ssh key for remote repositories, stored in a file, loaded by docker secrets
    external: true
    file: /some/where/secure/borg_ed25519.key
