#!/usr/bin/with-contenv bash

# Install DockerCLI if true
if [ "${DOCKERCLI}" == "true" ]; then
  echo "Installing Docker CLI and Compose..."
  apk add -U --quiet docker-cli docker-cli-compose
  export dockerver=$(docker --version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
  export composever=$(docker compose version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
else
  export dockerver="not installed"
  export composever="not installed"
fi

# Install additional packages
if [ -v EXTRA_PKGS ]
then
    echo Installing extra packages: "$EXTRA_PKGS"
    apk add -U --quiet $EXTRA_PKGS
fi