#!/command/with-contenv bash

# Install DockerCLI if true
if [ "${DOCKERCLI}" == "true" ]; then
  echo "[custom-init] Installing Docker CLI and Docker Compose..."
  apk add --no-cache -U --quiet docker-cli docker-cli-compose
else
  echo "[custom-init] Docker CLI variable not set, skipping..."
fi

# Install additional packages (space-separated list)
if [ -v EXTRA_PKGS ]; then
  echo "[custom-init] Installing extra packages: $EXTRA_PKGS"
  read -ra pkgs <<< "$EXTRA_PKGS"
  apk add --no-cache -U --quiet "${pkgs[@]}"
else
  echo "[custom-init] No custom packages found, skipping..."
fi
