#!/command/with-contenv bash

# Load the environment variables from the secrets service
if [ -f /etc/s6-overlay/env/cron-env ]; then
  source /etc/s6-overlay/env/cron-env
fi

# Version variables
borgver=$(borg --version)
borgmaticver=$(borgmatic --version)
apprisever=$(apprise --version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
pythonver=$(python3 --version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')

if [ "${DOCKERCLI}" == "true" ]; then
  dockerver=$(docker --version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
  composever=$(docker compose version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
else
  dockerver="not installed"
  composever="not installed"
fi

# Software versions
echo "-----------------------------------"
echo "Software Versions:
-----------------------------------
apprise $apprisever
$borgver
borgmatic $borgmaticver
dockercli $dockerver
composecli $composever
python $pythonver
-----------------------------------
Time Zone: $TZ
-----------------------------------"
if [ -v EXTRA_PKGS ]
then
  echo "Additional packages installed:"
  echo "-----------------------------------"
  echo $EXTRA_PKGS | tr -s " " "\n"
  echo "-----------------------------------"
fi

# Disable cron if it's set to disabled.
if [[ "$BACKUP_CRON" = "false" ]]; then
    echo "Disabling cron, removing configuration"
    # crontab -r # quite destructive
    # echo -n > /etc/crontabs/root # Empty config, doesn't look as nice with "crontab -l"
    echo "# Cron disabled" > /etc/crontabs/root
    echo "Cron is now disabled"
# Apply default or custom cron if $BACKUP_CRON is unset or set (not null):
elif [[ -v BACKUP_CRON ]]; then
    BACKUP_CRON="${BACKUP_CRON:-"0 1 * * *"}"
    CRON_COMMAND="${CRON_COMMAND:-"/usr/local/bin/borgmatic --stats -v 0 2>&1"}"
    echo "$BACKUP_CRON $CRON_COMMAND" > /etc/crontabs/root
    echo "Applying custom cron"
# If nothing is set, revert to default behaviour
else
    echo "Applying crontab.txt"
    crontab /etc/borgmatic.d/crontab.txt
fi

# Apply extra cron if it's set
if [ -v EXTRA_CRON ]
then
    echo "$EXTRA_CRON" >> /etc/crontabs/root
fi

# Current crontab var
crontab=$(crontab -l)

# Output cron settings to console
echo -e "Cron job set as: \n$crontab\n"

# Start Cron
exec /usr/sbin/crond -f -L /dev/stdout
